# Generated by Django 5.2.4 on 2025-07-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_content', models.TextField()),
                ('news_source', models.CharField(max_length=255)),
                ('news_created_at', models.DateTimeField(auto_now_add=True)),
                ('news_tags', models.ManyToManyField(related_name='news', to='Task02_02_00_News_Page_App.tag')),
            ],
        ),
    ]
