# Generated by Django 5.2.4 on 2025-07-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task01_00_00_News_Page_App', '0002_news_created_at_alter_news_tags_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='news_content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='news_created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='source',
            new_name='news_source',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='tags',
            new_name='news_tags',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='news_title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
